spring.application.name=TaskManager

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/taskmanager_db}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.security.jwt-secret=${JWT_SECRET}

app.frontend-url=${FRONTEND_URL:http://localhost:5173}
